version: 2
registeries:
  nuget-org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "CL-BuildPackaging"
    ignore:
      - dependency-name: "System.*"
      - dependency-name: "Microsoft.Win32.Registry.AccessControl"
      - dependency-name: "Microsoft.Windows.Compatibility"

  - package-ecosystem: "nuget"
    directory: "/tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility"
    schedule:
      interval: "daily"
    labels:
      - "CL-BuildPackaging"
    ignore:
      - dependency-name: "System.*"
      - dependency-name: "Microsoft.Win32.Registry.AccessControl"
      - dependency-name: "Microsoft.Windows.Compatibility"

  - package-ecosystem: "nuget"
    directory: "/tools/packaging/projects/reference/System.Management.Automation"
    schedule:
      interval: "daily"
    labels:
      - "CL-BuildPackaging"
    ignore:
      - dependency-name: "System.*"
      - dependency-name: "Microsoft.Win32.Registry.AccessControl"
      - dependency-name: "Microsoft.Windows.Compatibility"

  - package-ecosystem: "nuget"
    directory: "/test/tools/Modules"
    schedule:
      interval: "daily"
    labels:
      - "CL-BuildPackaging"
    ignore:
      - dependency-name: "System.*"
      - dependency-name: "Microsoft.Win32.Registry.AccessControl"
      - dependency-name: "Microsoft.Windows.Compatibility"

  - package-ecosystem: "nuget"
    directory: "/src/Modules"
    schedule:
      interval: "daily"
    labels:
      - "CL-BuildPackaging"
