name: Auto Assign PR Maintainer
on:
  pull_request:
    types: [opened, edited]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # using the `org/team_slug` or `/team_slug` syntax to add git team as reviewers
          assignees: |
            TravisEz13
            daxian-dbw
            adityapatwardhan
            iSazonov
            SeeminglyScience
          skipDraft: true
          skipKeywords: wip, draft
          addReviewers: false
          numberOfAssignees: 1
