name: 'Create reminder'

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read

jobs:
  reminder:
    if: github.repository_owner == 'PowerShell'

    permissions:
      issues: write  # for agrc/create-reminder-action to set reminders on issues
      pull-requests: write  # for agrc/create-reminder-action to set reminders on PRs
    runs-on: ubuntu-latest

    steps:
      - name: check for reminder
        uses: agrc/create-reminder-action@f57c0d69410c1db7d3ad6974b2a3f0a9c23db8f6 # v1.1.21
